/**
* HTML rendering methods for UI Components inside Layout
* require html container
* require damas.js
* call by process_hash function from main.js
*/


/**
* Input an Button for Search Component
* Localisation : Header
*/
var searchForm = document.createElement('form');
searchForm.className = 'searchForm';
var searchInput = document.createElement('input');
searchInput.className = 'searchInput';
var searchReset = document.createElement('div');
searchReset.className = 'searchReset clickable';
searchReset.innerHTML = 'X';
searchReset.addEventListener('click', function(){
    searchInput.value = '';
    document.location.hash = '';
});
searchForm.appendChild(searchInput);
searchForm.appendChild(searchReset);

var searchBt = document.createElement('a');
searchBt.className = 'searchBt clickable';
//    searchBt.setAttribute('href', '#search=');
searchBt.setAttribute('title', 'Search');

document.getElementById('headerCentral').appendChild(searchForm);
document.getElementById('headerCentral').appendChild(searchBt);

searchForm.addEventListener('submit', function(event) {
    if (searchInput.value.length > 0){
        addHash('search='+searchInput.value);
    }
    else {
        document.location.hash = '';
    }
});
searchBt.addEventListener('click', function(){
    searchForm.style.display = 'inline-block';
    searchBt.style.display = 'none';
    menuBts.style.display = 'none';
    searchReset.addEventListener('click', function(){
        searchForm.style.display = 'none';
        searchBt.style.display = 'block';
        menuBts.style.display = 'table-cell';
    });
});

/**
* Generate Component : Search Results
* 
*/
compSearch = (function(container, terms){
    // Temporary Table - To do : Replace with a table generated by search in db
    var resTable = document.createElement('table');
    resTable.className = 'resultsTable';
    resTable.innerHTML = 'results'
    var resTableLine = document.createElement('tr');
    resTable.appendChild(resTableLine);
    var resTableRow1 = document.createElement('td');
    var resTableRow2 = document.createElement('td');
    var resTableRow3 = document.createElement('td');
    var resTableRow1View = document.createElement('a');
//    logTableRow1View.setAttribute('href', '#view=nodeFile');
    resTableRow1View.innerHTML = 'viewNode';
    resTableRow2.id = 'btEditor';
    resTableRow2.innerHTML = 'editNode';
    resTableRow3.innerHTML = 'nodeKey';
    resTableRow1.appendChild(resTableRow1View);
    resTableLine.appendChild(resTableRow1);
    resTableLine.appendChild(resTableRow2);
    resTableLine.appendChild(resTableRow3);
    
    resTableRow1View.addEventListener('click', function(e){
        addHash('view=nodeFile');
    });
    
    resTableRow2.addEventListener('click', function(e){
        addHash('edit=nodeFile');
//        window.location.hash = '#edit=nodeFile';
    });
    
    // Component destination
    container.appendChild(resTable);
});